# docker exec -i -t packaging_packaging_1 gpg --import --batch credentials/sandbox.gpg
version: '3'
services:
  packaging:
    image: jenkinsciinfra/packaging:latest
    command: "sleep 99d"
    environment:
    - "BUILDENV=/srv/releases/jenkins/env/test.mk"
    - "BRANDING_DIR=/srv/releases/jenkins/branding"
    - "BRAND=/srv/releases/jenkins/branding/test.mk"
    - "CREDENTIAL=/srv/releases/jenkins/credentials/test.mk"
    - "GPG_FILE=/srv/releases/jenkins/credentials/sandbox.gpg"
    - "GPG_KEYNAME=Bogus Test"
    - "GPG_PASSPHRASE=s3cr3t"
    - "GPG_PASSPHRASE_FILE=/srv/releases/jenkins/credentials/test.gpg.password.txt"
    - "WAR=/srv/releases/jenkins/jenkins.war"
    volumes:
      - .:/srv/releases/jenkins
    working_dir: "/srv/releases/jenkins"
